### Loading user data from the CSV file

In [3]:
import pandas as pd
df = pd.read_csv("users.csv")
display(df)

                name                 email
0      Husna Hussain     husna@example.com
1        Ankit Kumar     ankit@example.com
2      Amisha Bharti    amisha@example.com
3       Prachi Priya    prachi@example.com
4      Madhuja Singh   madhuja@example.com
5      Anjali Sharma    anjali@example.com
6         Soni Singh      soni@example.com
7   Bhaskar Bhardwaj   bhaskar@example.com
8   Kaustuv Kanhaiya   kaustuv@example.com
9       Udipta Kumar    udipta@example.com
10  Shadmani Hussain  shadmani@example.com
11      Shilpa Sinha    shilpa@example.com
12     Bajrang Kumar   bajrang@example.com

### Initializing the SQLite database and creating the 'users' table

In [5]:
import sqlite3

connection = sqlite3.connect("users.db")
cursor = connection.cursor()

cursor.execute("""
    CREATE TABLE IF NOT EXISTS users (
        id INTEGER PRIMARY KEY AUTOINCREMENT,
        name TEXT NOT NULL,
        email TEXT NOT NULL
    )
""")

connection.commit()

print("Database created successfully!")

Database created successfully!

### Iterating through the DataFrame and inserting each record into the database

In [6]:
for _, row in df.iterrows():

    cursor.execute("""
        INSERT INTO users (name, email)
        VALUES (?, ?)
    """, (
        row["name"],
        row["email"]
    ))

connection.commit()

print("CSV data inserted successfully!")

CSV data inserted successfully!

### Querying and displaying all records stored in the 'users' table

In [7]:
result = pd.read_sql_query(
    "SELECT * FROM users",
    connection
)

display(result)

    id              name                 email
0    1     Husna Hussain     husna@example.com
1    2       Ankit Kumar     ankit@example.com
2    3     Amisha Bharti    amisha@example.com
3    4      Prachi Priya    prachi@example.com
4    5     Madhuja Singh   madhuja@example.com
5    6     Anjali Sharma    anjali@example.com
6    7        Soni Singh      soni@example.com
7    8  Bhaskar Bhardwaj   bhaskar@example.com
8    9  Kaustuv Kanhaiya   kaustuv@example.com
9   10      Udipta Kumar    udipta@example.com
10  11  Shadmani Hussain  shadmani@example.com
11  12      Shilpa Sinha    shilpa@example.com
12  13     Bajrang Kumar   bajrang@example.com
13  14     Husna Hussain     husna@example.com
14  15       Ankit Kumar     ankit@example.com
15  16     Amisha Bharti    amisha@example.com
16  17      Prachi Priya    prachi@example.com
17  18     Madhuja Singh   madhuja@example.com
18  19     Anjali Sharma    anjali@example.com
19  20        Soni Singh      soni@example.com
20  21  Bhaskar Bhardwaj   bhaskar@example.com
21  22  Kaustuv Kanhaiya   kaustuv@example.com
22  23      Udipta Kumar    udipta@example.com
23  24  Shadmani Hussain  shadmani@example.com
24  25      Shilpa Sinha    shilpa@example.com
25  26     Bajrang Kumar   bajrang@example.com